packages:
  core: !include atom-echos3r-voice.yaml

esphome:
  project:
    name: dflourusso.atom-echos3r-voice
    version: dev # Replaced by the release workflow with the workflow_dispatch version

http_request:

ota:
  - platform: http_request
    id: ota_http_request

update:
  - platform: http_request
    name: Firmware
    device_class: firmware
    source: https://dflourusso.github.io/atom-echos3r-voice/firmware/manifest.json
